### ISSUE TITLE
Apple and Snake head positions may overlap.

### ISSUE THREAD

**Issue by SivaramPg** [SivaramPg/JS_Snake_Game#11]
Need to check at start whether the apple and snake positions are not overlapping.
![snake and apple overlap issue](https://user-images.githubusercontent.com/39243686/42550197-e8883b92-84ed-11e8-9a38-2bd312455b67.PNG)

**Comment by ojaswa1942** [comment]
The loop was meant to do this! I think it just stops it from completely overlapping

**Comment by SivaramPg** [comment]
I have removed it for now... I think we should do these checks externally and let these functions be standalone functions.

**Comment by ojaswa1942** [comment]
Then please find a solution. Don't delete code without an alternative

**Comment by SivaramPg** [comment]
Need to make a function that checks if the coordinates of apple fall in any region of the snake.

**Comment by ojaswa1942** [comment]
Since now the snake is moving, if that happens, apple will increment it position the exact moment.. and they will seem different
But it will cause a problem when snake length is increased

**Comment by ojaswa1942** [comment]
Check for snake body has also been implemented
