### ISSUE TITLE
Apple and snake paths need to line up...

### ISSUE THREAD

**Issue by SivaramPg** [SivaramPg/JS_Snake_Game#12]
Currently the random X and Y positioning of Apple does not suit this game and when we animate the snake there is not guarantee they will line up as we require them to do.

![snake and apple misalignment issue](https://user-images.githubusercontent.com/39243686/42551018-ac3c9c28-84f2-11e8-89de-844c2266f0e0.PNG)
 
There needs to be a way to make sure both X and Y positions increment by set amounts so the snake path is aligned to the apple like following grids without actually showing grids.

**Comment by SivaramPg** [comment]
Apple element now moves in steps of 30, ie (0,0) ,(0,30), (1200, 90) etc for x and y values.

**Comment by ojaswa1942** [comment]
I couldn't understand the problem. Can you please re-frame the issue?

**Comment by SivaramPg** [comment]
The path that the snake takes when it starts to move should line up with the position of apple... as you can see currently if the snake moves down then it will not be in line with the apple and that is an issue.

**Comment by ojaswa1942** [comment]
Done with grid system
