### ISSUE TITLE
Fix the game area which is shifted to the top left corner.

### ISSUE THREAD

**Issue by SivaramPg** [SivaramPg/JS_Snake_Game#14]
The game depending on the canvas size may ignore some area of the canvas in its current state.
**Need to center the game in the canvas or make the canvas size a desirable one.**

**Comment by ojaswa1942** [comment]
Is this the same problem, which is causing the snake to travel beyond lower and right boundary?
If not, I'd raise another issue

**Comment by ojaswa1942** [comment]
![This happens with bottom border](https://user-images.githubusercontent.com/35270649/42584422-caefb764-8550-11e8-86ca-39d8bb30ec48.png)
This happens with bottom border
ALSO,
At the right border, the block completely disappears travels in the grid beyond border

**Comment by SivaramPg** [comment]
I will have to take a look

**Comment by SivaramPg** [comment]
This should not be happening.!

**Comment by SivaramPg** [comment]
It is working fine at my end... x and y grids are showing one less than the max possible grid.
The code looks fine nothing looks as if it can be causing this issue. grid positions are returning one value less than the max possible ...so the boxes should never go near the bottom or right borders

**Comment by ojaswa1942** [comment]
Check that with multiple canvas sizes

**Comment by SivaramPg** [comment]
Trying a fix now.... Please wait a moment.

**Comment by SivaramPg** [comment]
Do we want the snake to go visually out of bounds or stay inside the canvas.

**Comment by ojaswa1942** [comment]
Doesn't matters
![screenshot from 2018-07-11 22-19-42](https://user-images.githubusercontent.com/35270649/42587680-195f4a06-8559-11e8-82f4-40202abb6629.png)
As long as this extra space doesn't comes!

**Comment by SivaramPg** [comment]
Extra space does come at this point of time.

**Comment by ojaswa1942** [comment]
It shouldn't if we incorporating a grid system and height & width of canvas are divisible by 30!

**Comment by SivaramPg** [comment]
Will do that now.

**Comment by SivaramPg** [comment]
Review the fixes in the pull request.

**Comment by ojaswa1942** [comment]
Just the collision occurs after the grid next to borders! I think I know how to correct it ;)

**Comment by ojaswa1942** [comment]
Done!

**Comment by SivaramPg** [comment]
Nice.
