### ISSUE TITLE
Load event listener on window does not retrigger after initially scrolling to canvas

### ISSUE THREAD

**Issue by SivaramPg** [SivaramPg/JS_Snake_Game#6]
Event listener triggers function to initially scroll to canvas but after scroll activity the App does not retrigger the event and scroll to Canvas on refresh on multiple browsers.

**Comment by ojaswa1942** [comment]
Solved!
Bypassed by modifying the display..
Will close the bug after merging

**Comment by SivaramPg** [comment]
Good Job!
