### ISSUE TITLE
Snake head not exactly in center

### ISSUE THREAD

**Issue by ojaswa1942** [SivaramPg/JS_Snake_Game#8]
Again, probably because view changes made for resize.

**Comment by SivaramPg** [comment]
Snake is now in the *center of canvas* and uses ```canvas.width``` and ```canvas.height``` for all its calculations instead of the larger window object now containing both header and footer.

*Vertical misalignment fixed by changing -* 
``` JavaScript 
canvas.height = window.innerHeight -headerHeight - headerHeight;
```
``` JavaScript 
canvas.height = window.innerHeight -headerHeight -footerHeight;
```
